[package]
name = "pet-uv"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
pet-core = { path = "../pet-core" }
pet-fs = { path = "../pet-fs" }
pet-python-utils = { path = "../pet-python-utils" }
log = "0.4.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"