[package]
name = "pet-core"
version = "0.1.0"
edition = "2021"

[dependencies]
pet-fs = { path = "../pet-fs" }
pet-python-utils = { path = "../pet-python-utils" }
serde = { version = "1.0.152", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.10.4"
log = "0.4.21"
serde_json = "1.0.93"
