[package]
name = "pet-telemetry"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "windows")'.dependencies]
msvc_spectre_libs = { version = "0.1.1", features = ["error"] }

[dependencies]
pet-core = { path = "../pet-core" }
pet-fs = { path = "../pet-fs" }
pet-python-utils = { path = "../pet-python-utils" }
log = "0.4.21"
env_logger = "0.10.2"
lazy_static = "1.4.0"
regex = "1.10.4"
